# Generated by Django 5.0.4 on 2024-06-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Poor"),
                    (2, "Fair"),
                    (3, "Good"),
                    (4, "Very Good"),
                    (5, "Excellent"),
                ],
                default=3,
            ),
        ),
    ]
